# Generated by Django 6.0.6 on 2026-08-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
