# Generated by Django 6.0.3 on 2026-06-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='category',
            field=models.CharField(choices=[('expedition', 'Expédition'), ('trekking', 'Trekking'), ('bivouac', 'Bivouac'), ('camping', 'Camping'), ('photography', 'Photography'), ('wildlife', 'Wildlife'), ('cultural', 'Cultural')], max_length=20),
        ),
    ]
