# Generated by Django 6.0.3 on 2026-06-10 19:00

import django.core.validators
import expeditions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_alter_expedition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=expeditions.validators.cover_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), expeditions.validators.FileSizeValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='expeditionimage',
            name='image',
            field=models.ImageField(upload_to=expeditions.validators.gallery_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), expeditions.validators.FileSizeValidator(10485760)]),
        ),
    ]
