/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          forest: '#4A5D45',
          forestDark: '#162C1C',
          orange: '#A64B1D',
          orangeDark: '#A23F0A',
          sand: '#F4E7D3',
          bg: '#F9F9F7',
          dark: '#1A1C1B',
        },
        primary: "#2c4231",
        "on-secondary-fixed-variant": "#7d2d00",
        "on-primary-fixed-variant": "#364c3a",
        "secondary-fixed": "#ffdbcd",
        "inverse-surface": "#2d3135",
        "surface-container-high": "#e5e8ee",
        "on-surface-variant": "#434842",
        "outline": "#737972",
        "inverse-on-surface": "#eef1f6",
        "on-tertiary-fixed": "#201b0c",
        "on-surface": "#181c20",
        "on-error": "#ffffff",
        "on-tertiary-container": "#d0c7af",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#360f00",
        "tertiary-fixed-dim": "#cfc6ae",
        "surface-dim": "#d7dadf",
        "primary-fixed": "#d0e9d1",
        "error": "#ba1a1a",
        "surface-container-low": "#f1f4f9",
        "primary-fixed-dim": "#b4cdb6",
        "outline-variant": "#c3c8c0",
        "on-secondary-container": "#6e2700",
        "surface-container-highest": "#e0e3e8",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface": "#f7f9ff",
        "surface-variant": "#e0e3e8",
        "on-primary-fixed": "#0b2011",
        "secondary": "#9f410f",
        "tertiary": "#423c2b",
        "on-primary-container": "#b6cfb8",
        "tertiary-fixed": "#ece2c9",
        "on-tertiary-fixed-variant": "#4c4634",
        "inverse-primary": "#b4cdb6",
        "surface-tint": "#4d6451",
        "background": "#f7f9ff",
        "surface-bright": "#f7f9ff",
        "primary-container": "#435947",
        "secondary-container": "#fe8852"
      },
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        epilogue: ['Epilogue', 'sans-serif'],
        work: ['Work Sans', 'sans-serif'],
        space: ['Space Grotesk', 'sans-serif'],
      },
      boxShadow: {
        'brutalist-orange': '4px 4px 0px 0px #A64B1D',
        'brutalist-forest': '4px 4px 0px 0px #162C1C',
        'brutalist-dark': '4px 4px 0px 0px #1A1C1B',
        'brutalist-sand': '4px 4px 0px 0px #F4E7D3',
        'brutalist-white': '4px 4px 0px 0px #FFFFFF',
        'brutalist-thick-dark': '6px 6px 0px 0px #1A1C1B',
      }
    },
  },
  plugins: [],
}
