# Generated by Django 6.0.6 on 2026-09-01 12:35

import django.core.validators
import inquiries.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='selfie',
            field=models.ImageField(help_text='A single selfie photo of the participant (max 5 MB).', null=True, upload_to=inquiries.validators.selfie_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), inquiries.validators.FileSizeValidator(5242880)]),
        ),
    ]
